project:
  type: website
  output-dir: docs

website:
  title: "Basso Canavese Volley 2024/2025"
  favicon: images/foxvolleyball3.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



