---
title: "BCV Settore Giovanile Femminile"
format: 
  dashboard:
    nav-buttons: [github]
    github: https://github.com/mine-cetinkaya-rundel/ld-dashboard
logo: ../images/logo.png
theme: [sandstone, theme/custom.scss]
fig-width: 10
fig-asp: 0.3
params:
  year: "2024/2025"
  societa: "Basso Canavese Volley"
  settore: "Giovanile"
  genere: "Femminile"
  anni: "2012 - 2013"
editor_options: 
  chunk_output_type: console
---

```{r}
#| label: load-packages
#| message: false

library(tidyverse)
library(readxl)
library(scales)
library(DT)
library(gt)
theme_set(theme_minimal(base_size = 24, base_family = "Atkinson Hyperlegible"))
library(bslib)
library(bsicons)
```

```{r}
#| label: load-data
#| message: false

ld <- read_excel("../data/ld.xlsx")
```

```{r}
#| label: set-inputs

time_period <- paste(params$year)
```

#  {.sidebar}

Questa dashboard mostra le statistiche per:

|              |                     |
|--------------|---------------------|
| **Società** | `{r} params$societa` |
| **Settore**     | `{r} params$settore`  |
| **Genere** | `{r} params$genere` |
| **Anni di nascita** | `{r} params$anni` |
| **Stagione**    | `{r} time_period`   |

------------------------------------------------------------------------

Nella stagione `{r} time_period` nel settore `{r} params$settore` (`{r} params$genere`) 
sono presenti 3 squadre con il seguente numero di atleti:

|                          |     |
|--------------------------|-----|
| **U13 FIPAV** |  14 |
| **U13 UISP**            |  14 |
| **U12 UISP**               |  14 |

------------------------------------------------------------------------

::: {.callout-note collapse="true"}
## Disclaimer

This is a test
:::


# U13 FIPAV


## Row {height="20%"}

```{r}
#| content: valuebox
#| title: "Allenamenti"

list(
  icon = "file-medical",
  color = "primary",
  value = 20
)
```

```{r}
#| content: valuebox
#| title: "Partite giocate"

list(
  icon = "clipboard2-pulse",
  color = "red",
  value = 20
)
```

```{r}
#| content: valuebox
#| title: "Partite vinte"

list(
  icon = "clipboard2-pulse",
  color = "red",
  value = 20
)
```

## Row {height="80%"}

### Ciao


# U13 UISP


## Row {height="20%"}

```{r}
#| content: valuebox
#| title: "Allenamenti"

list(
  icon = "file-medical",
  color = "primary",
  value = 20
)
```

```{r}
#| content: valuebox
#| title: "Partite giocate"

list(
  icon = "clipboard2-pulse",
  color = "red",
  value = 20
)
```

```{r}
#| content: valuebox
#| title: "Partite vinte"

list(
  icon = "clipboard2-pulse",
  color = "red",
  value = 20
)
```

## Row {height="80%"}


# U12 UISP


## Row {height="20%"}

```{r}
#| content: valuebox
#| title: "Allenamenti"

list(
  icon = "file-medical",
  color = "primary",
  value = 20
)
```

```{r}
#| content: valuebox
#| title: "Partite giocate"

list(
  icon = "clipboard2-pulse",
  color = "red",
  value = 20
)
```

```{r}
#| content: valuebox
#| title: "Partite vinte"

list(
  icon = "clipboard2-pulse",
  color = "red",
  value = 20
)
```

## Row {height="80%"}